language: ruby
rvm:
  - "2.6.7"
  - "2.7.3"
  - "3.0.1"
env:
  - TMUX_VERSION=3.2
  - TMUX_VERSION=3.1c
  - TMUX_VERSION=3.1b
  - TMUX_VERSION=3.1a
  - TMUX_VERSION=3.1
  - TMUX_VERSION=3.0a
  - TMUX_VERSION=3.0
  - TMUX_VERSION=2.9a
  - TMUX_VERSION=2.9
  - TMUX_VERSION=2.8
  - TMUX_VERSION=2.7
  - TMUX_VERSION=2.6
  - TMUX_VERSION=2.5
  - TMUX_VERSION=2.4
  - TMUX_VERSION=2.3
  - TMUX_VERSION=2.2
  - TMUX_VERSION=2.1
  - TMUX_VERSION=2.0
  - TMUX_VERSION=1.9
  - TMUX_VERSION=1.8
  - TMUX_VERSION=1.7
  - TMUX_VERSION=1.6
  - TMUX_VERSION=1.5
matrix:
  allow_failures:
    - env: TMUX_VERSION=1.7
before_install:
  - gem install bundler
  - sudo apt-get update -qq
  - sudo apt-get install -qq libevent-dev libncurses-dev
  - git clone https://github.com/tmux/tmux.git tmux
  - cd tmux
  - git checkout $TMUX_VERSION
  - sh autogen.sh
  - ./configure && make && sudo make install
  - cd ..
  - tmux -V
script: bundle exec rake test
